### ISSUE TITLE
Deliverables

### ISSUE THREAD

**Issue by deryacbn** [Inf166/pwa-peer-to-peer-sharing-recipes#15]
Zu Erledigen (braucht noch einen eigenen Issue und wird nicht in einem bisherigen erledigt)

- [x] Was ist das Nutzungsproblem, dass mit und in dem Projekt adressiert werden soll? #7 
- [x] Welche Entwicklungsziele (Zielhierarchie auf strategischer, taktischer und operativer Ebene) werden mit dem Projekt für das inter aktive System angestrebt? #41 
- [x] Wer sind die Stakeholder? #26 
- [x] Wer sind die Benutzer? #28 
- [ ] Wie sieht ein valides Modell der Nutzungskontexte aus? **(ISO 215-450)**
- [x] Welches sind die Ziele/Handlungen/Tätigkeiten/Aufgaben der Menschen, die das System unterstützen muss bzw. soll; welche Struktur weisen die Handlungen auf und in welchen Beziehungen stehen die Handlungen zueinander? #31 
- [x] Welche Paradigmen und Metaphern liegen in der Anwendungsdomäne vor? #44
- [x] Welche Erfordernisse liegen in der Anwendungsdomäne vor? #31 
- [x] Welche funktionalen und qualitativen Anforderungen können aus den Erfordernissen abgeleitet werden? #32 
- [x] Welche organisatorischen Anforderungen liegen vor?  #32 
- [ ] Wie soll methodisch im Projekt vorgegangen werden? Wie werden die beiden Perspektiven in EINEM Projekt systematisch und strukturiert berücksichtigt? Vorgehensmodelle? (Begründung und kritische Diskussion der Alternativen notwendig.) **(ISO 215-450 & agile Entwicklung)**
- [x] Welches ist das konzeptuelle Modell für die präskriptiven Handlungsmodelle? Welche Bezüge existieren bzgl. der Entwicklungsziele? #35 
- [x] Welche alternativen konzeptuellen Modelle wurden entwickelt und wie wurde mit Design-Alternativen verfahren? #37 
- [x] Welche Interaktions-Paradigmen, -Modi und -Stile wurden in Betracht gezogen? (Erörterung notwendig.) #37 #38 
- [x] Welche Prototypen wurden entwickelt? Was zeichnet die verschiedenen Prototypen-Alternativen aus und wie wurde eine Synthese der Alternativen erreicht? #43
- [x] Welche Anwendungslogik ist zu implementieren, um die wichtigsten Anwendungsfälle mit dem System zu ermöglichen? #34 
- [x] Welche Algorithmen werden dazu implementiert? Welche Objekte aus dem konzeptuellen Modell werden mit der Anwendungslogik adressiert/modifiziert? #43
- [x] Nach welchen Kriterien wurden die Evaluation-Methoden und -Techniken ausgewählt und kombiniert? #39 #38 
- [x] Welches sind die Evaluationsergebnisse, welchen Erfüllungsgrad der Entwicklungsziele weisen die finalen Designlösungen auf? #39 #38 
- [x] Welche Konsequenzen ergeben sich daraus für weitere Schritte/Iterationen? #39 #38 
- [x] Welche Einflüsse (positive sowie negative Auswirkungen, Chancen und Gefahren/Bedrohungen) auf die Nutzungskontexte werden durch die Bereitstellung des zukünftigen Systems erwartet? #30
