### ISSUE TITLE
(Organisation) - Projektplan

### ISSUE THREAD

**Issue by mai-space** [Inf166/pwa-peer-to-peer-sharing-recipes#42]
```
GanttStart: 2020-11-17T14:00:00+01:00
GanttDue: 2020-11-24T16:00:00+01:00
```

- [x] [Problemstellung ](https://github.com/Inf166/EPWS2020CobanMai#was-ist-unser-problemraum)und Herleitung der [Zielsetzung ](https://github.com/Inf166/EPWS2020CobanMai#unsere-vision-und-ziel)
- [x] [Zielsetzungen sowie Begründung des Vorgehens zur Erreichung dieser](https://github.com/Inf166/EPWS2020CobanMai/issues/41 )
- [x] [Erläuterung der Abwägung der gewählten Methoden im Vorgehen](https://github.com/Inf166/EPWS2020CobanMai/issues/41 )
- [x] [ggf. erste Modellierungen und Modellierungsbegründungen](https://github.com/Inf166/EPWS2020CobanMai/issues/26 )
- [x] Beispiele für Artefakte: [Domänenmodell]https://github.com/Inf166/EPWS2020CobanMai/issues/7 ), [Zielhierarchie](https://github.com/Inf166/EPWS2020CobanMai/issues/41 ), [Projektplan](https://github.com/Inf166/EPWS2020CobanMai/issues/42 ), [Alleinstellungsmerkmale](https://github.com/Inf166/EPWS2020CobanMai#2-wirtschaftliche-relevanz), erste [Risiken](https://github.com/Inf166/EPWS2020CobanMai/issues/30 ), [Spezifikation des ersten technischen/architekturellen Proof-of-Concepts (PoC)](https://github.com/Inf166/EPWS2020CobanMai/issues/43 ), ...
- [x] Deliverables für den 2. Audit ([Projektplan](https://github.com/Inf166/EPWS2020CobanMai/issues/42))

Gantt Diagramm mit [GanttLab](https://app.ganttlab.com/)
Projektplanung: Agil
