### ISSUE TITLE
(Audit Zwei) - Feedback und resultierende ToDo's

### ISSUE THREAD

**Issue by mai-space** [Inf166/pwa-peer-to-peer-sharing-recipes#57]
- [x] User Profiles Bezeichnungen (Bezeichnungen stammen aus dem Marketing, bitte für HCI anpassen)
- [x] Napster Serverarchitektur (Als Beispiel für mögliche Serverarchitektur für uns? Sicherheit der Daten)
  - [x] Asynchrone Teile / Synchrone Teile
- [x] Problemszenarien -> Claims Analyse
- [ ] ~(Optional) Zutaten Beschaffenheit~
- [ ] ~Technisches Risiko: Cache Swapping/Paging beschäftigen~
